[tool.poetry]
name = "map-tools"
version = "0.9.2"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
ipycytoscape = "^1.2.2"
mapknowledge = {url = "https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.9.2/mapknowledge-0.9.2-py3-none-any.whl"}
notebook = "^6.4.8"
